#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import agenda_pb2 as agenda__pb2


class AgendaStub(object):
  """interface de serviço
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddContato = channel.unary_unary(
        '/Agenda/AddContato',
        request_serializer=agenda__pb2.Contato.SerializeToString,
        response_deserializer=agenda__pb2.Msg.FromString,
        )
    self.RmContato = channel.unary_unary(
        '/Agenda/RmContato',
        request_serializer=agenda__pb2.Contato.SerializeToString,
        response_deserializer=agenda__pb2.Msg.FromString,
        )
    self.ListContato = channel.unary_stream(
        '/Agenda/ListContato',
        request_serializer=agenda__pb2.Request.SerializeToString,
        response_deserializer=agenda__pb2.Contato.FromString,
        )


class AgendaServicer(object):
  """interface de serviço
  """

  def AddContato(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RmContato(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListContato(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AgendaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddContato': grpc.unary_unary_rpc_method_handler(
          servicer.AddContato,
          request_deserializer=agenda__pb2.Contato.FromString,
          response_serializer=agenda__pb2.Msg.SerializeToString,
      ),
      'RmContato': grpc.unary_unary_rpc_method_handler(
          servicer.RmContato,
          request_deserializer=agenda__pb2.Contato.FromString,
          response_serializer=agenda__pb2.Msg.SerializeToString,
      ),
      'ListContato': grpc.unary_stream_rpc_method_handler(
          servicer.ListContato,
          request_deserializer=agenda__pb2.Request.FromString,
          response_serializer=agenda__pb2.Contato.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Agenda', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
