#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agenda.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agenda.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x61genda.proto\")\n\x07\x43ontato\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x10\n\x08telefone\x18\x02 \x01(\t\"\x17\n\x03Msg\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\x1a\n\x07Request\x12\x0f\n\x07request\x18\x01 \x01(\t2n\n\x06\x41genda\x12\x1e\n\nAddContato\x12\x08.Contato\x1a\x04.Msg\"\x00\x12\x1d\n\tRmContato\x12\x08.Contato\x1a\x04.Msg\"\x00\x12%\n\x0bListContato\x12\x08.Request\x1a\x08.Contato\"\x00\x30\x01\x62\x06proto3')
)




_CONTATO = _descriptor.Descriptor(
  name='Contato',
  full_name='Contato',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='Contato.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telefone', full_name='Contato.telefone', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=57,
)


_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='Msg.mensagem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=82,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='Request.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['Contato'] = _CONTATO
DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Contato = _reflection.GeneratedProtocolMessageType('Contato', (_message.Message,), dict(
  DESCRIPTOR = _CONTATO,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:Contato)
  ))
_sym_db.RegisterMessage(Contato)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:Msg)
  ))
_sym_db.RegisterMessage(Msg)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'agenda_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)



_AGENDA = _descriptor.ServiceDescriptor(
  name='Agenda',
  full_name='Agenda',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=112,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddContato',
    full_name='Agenda.AddContato',
    index=0,
    containing_service=None,
    input_type=_CONTATO,
    output_type=_MSG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RmContato',
    full_name='Agenda.RmContato',
    index=1,
    containing_service=None,
    input_type=_CONTATO,
    output_type=_MSG,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListContato',
    full_name='Agenda.ListContato',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_CONTATO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENDA)

DESCRIPTOR.services_by_name['Agenda'] = _AGENDA

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class AgendaStub(object):
    """interface de serviço
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.AddContato = channel.unary_unary(
          '/Agenda/AddContato',
          request_serializer=Contato.SerializeToString,
          response_deserializer=Msg.FromString,
          )
      self.RmContato = channel.unary_unary(
          '/Agenda/RmContato',
          request_serializer=Contato.SerializeToString,
          response_deserializer=Msg.FromString,
          )
      self.ListContato = channel.unary_stream(
          '/Agenda/ListContato',
          request_serializer=Request.SerializeToString,
          response_deserializer=Contato.FromString,
          )


  class AgendaServicer(object):
    """interface de serviço
    """

    def AddContato(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def RmContato(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ListContato(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_AgendaServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'AddContato': grpc.unary_unary_rpc_method_handler(
            servicer.AddContato,
            request_deserializer=Contato.FromString,
            response_serializer=Msg.SerializeToString,
        ),
        'RmContato': grpc.unary_unary_rpc_method_handler(
            servicer.RmContato,
            request_deserializer=Contato.FromString,
            response_serializer=Msg.SerializeToString,
        ),
        'ListContato': grpc.unary_stream_rpc_method_handler(
            servicer.ListContato,
            request_deserializer=Request.FromString,
            response_serializer=Contato.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Agenda', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAgendaServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """interface de serviço
    """
    def AddContato(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def RmContato(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ListContato(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAgendaStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """interface de serviço
    """
    def AddContato(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    AddContato.future = None
    def RmContato(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    RmContato.future = None
    def ListContato(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_Agenda_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Agenda', 'AddContato'): Contato.FromString,
      ('Agenda', 'ListContato'): Request.FromString,
      ('Agenda', 'RmContato'): Contato.FromString,
    }
    response_serializers = {
      ('Agenda', 'AddContato'): Msg.SerializeToString,
      ('Agenda', 'ListContato'): Contato.SerializeToString,
      ('Agenda', 'RmContato'): Msg.SerializeToString,
    }
    method_implementations = {
      ('Agenda', 'AddContato'): face_utilities.unary_unary_inline(servicer.AddContato),
      ('Agenda', 'ListContato'): face_utilities.unary_stream_inline(servicer.ListContato),
      ('Agenda', 'RmContato'): face_utilities.unary_unary_inline(servicer.RmContato),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Agenda_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Agenda', 'AddContato'): Contato.SerializeToString,
      ('Agenda', 'ListContato'): Request.SerializeToString,
      ('Agenda', 'RmContato'): Contato.SerializeToString,
    }
    response_deserializers = {
      ('Agenda', 'AddContato'): Msg.FromString,
      ('Agenda', 'ListContato'): Contato.FromString,
      ('Agenda', 'RmContato'): Msg.FromString,
    }
    cardinalities = {
      'AddContato': cardinality.Cardinality.UNARY_UNARY,
      'ListContato': cardinality.Cardinality.UNARY_STREAM,
      'RmContato': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Agenda', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
